In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split
from sklearn import preprocessing, tree
from sklearn.utils import shuffle
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
_diseases = ["stroke", "heart_attack", "diabetes"]

In [3]:
#Create dataframes containing data for people who did and didn't develop x diseases
#Probably don't merge data frames (could be done at a later stage but probably doesn't work in our timeframe, requires too much data cleaning)

In [4]:
#Create a model to predict based off all of the features in the dataset for each disease
#Proabably use a neural network? Some kind of ensemble learning method

In [5]:
#Create models to impute missing input features based on the features that the user does provide
#Develop a confidence interval for the missing values, create an input vector with each quartile (?) from the confidence interval

In [6]:
#Take in user input
#Predict likelihood of development of each disease
#Use each input vector if we had to create a confidence interval imputation for missing data
#Create a confidence interval for likelhood of developing disease

In [7]:
#Determine which of the features contributed the most (?) to the likelihood of the more likely diseases
#Make recommendations for how to reduce the likelhiood of the diseases based on these features

In [8]:
df = pd.read_csv("2015.csv")
df = df[["BPHIGH4", "BPMEDS", "SEX", "TOLDHI2", "CVDINFR4", "CVDSTRK3", "DIABETE3", "WEIGHT2", "HEIGHT3", "SMOKE100", "SMOKDAY2", "DRNK3GE5", "_AGE80", "_FRUTSUM", "_VEGESUM", "_PA150R2", "_RACEGR3"]]
df.head()

,BPHIGH4,BPMEDS,SEX,TOLDHI2,CVDINFR4,CVDSTRK3,DIABETE3,WEIGHT2,HEIGHT3,SMOKE100,SMOKDAY2,DRNK3GE5,_AGE80,_FRUTSUM,_VEGESUM,_PA150R2,_RACEGR3
0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,280.0,510.0,1.0,3.0,NaN,63.0,50.0,217.0,3.0,1.0
1,3.0,NaN,2.0,2.0,2.0,2.0,3.0,165.0,508.0,1.0,1.0,NaN,52.0,24.0,78.0,1.0,1.0
2,3.0,NaN,2.0,1.0,7.0,1.0,3.0,158.0,511.0,NaN,NaN,NaN,71.0,NaN,NaN,9.0,1.0
3,1.0,1.0,2.0,1.0,2.0,2.0,3.0,180.0,507.0,2.0,NaN,NaN,63.0,100.0,20.0,3.0,1.0
4,3.0,NaN,2.0,2.0,2.0,2.0,3.0,142.0,504.0,2.0,NaN,NaN,61.0,NaN,200.0,3.0,1.0

In [9]:
df = df[df["HEIGHT3"] != 7777.0]
df = df[df["HEIGHT3"] != 9999.0]
df = df[df["WEIGHT2"] != 7777.0]
df = df[df["WEIGHT2"] != 9999.0]

In [10]:
df.describe()

,BPHIGH4,BPMEDS,SEX,TOLDHI2,CVDINFR4,CVDSTRK3,DIABETE3,WEIGHT2,HEIGHT3,SMOKE100,SMOKDAY2,DRNK3GE5,_AGE80,_FRUTSUM,_VEGESUM,_PA150R2,_RACEGR3
count,412999.000000,166838.000000,413000.000000,358034.000000,413000.000000,413000.000000,412993.000000,407685.000000,407369.000000,400846.000000,175276.000000,201379.000000,413000.000000,3.755700e+05,3.689370e+05,413000.000000,413000.000000
mean,2.206155,1.173641,1.560460,1.623659,1.965128,1.971663,2.756938,196.126544,555.154678,1.598976,2.432849,67.468837,55.433254,1.361374e+02,1.943727e+02,2.546293,1.652012
std,1.027882,0.445738,0.496332,0.718881,0.426887,0.334988,0.714990,397.807382,562.901366,0.701376,0.881476,36.053693,17.132764,1.375521e+02,1.549042e+02,2.409574,1.472622
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,50.000000,204.000000,1.000000,1.000000,1.000000,18.000000,5.397605e-79,5.397605e-79,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,145.000000,504.000000,1.000000,2.000000,77.000000,43.000000,5.700000e+01,1.100000e+02,1.000000,1.000000
50%,3.000000,1.000000,2.000000,2.000000,2.000000,2.000000,3.000000,172.000000,507.000000,2.000000,3.000000,88.000000,58.000000,1.000000e+02,1.680000e+02,2.000000,1.000000
75%,3.000000,1.000000,2.000000,2.000000,2.000000,2.000000,3.000000,200.000000,510.000000,2.000000,3.000000,88.000000,69.000000,2.000000e+02,2.430000e+02,3.000000,1.000000
max,9.000000,9.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9501.000000,9503.000000,9.000000,9.000000,99.000000,80.000000,1.500000e+04,1.992900e+04,9.000000,9.000000

In [11]:
def fix_height(height):
    if height <= 711:
        feet = height // 100
        inches = height % 100 + 12 * feet
    else:
        meters = height // 100
        centimeters = height % 100 + 12 * meters
        inches = centimeters / 2.54
    return inches

In [12]:
def fix_weight(weight):
    if weight <= 999:
        lbs = weight
    else:
        kilos = weight - 9000
        lbs = kilos / 2.2
    return lbs

In [13]:
df["height"] = df["HEIGHT3"].apply(fix_height)
df["weight"] = df["WEIGHT2"].apply(fix_weight)
df.drop(["HEIGHT3", "WEIGHT2"], axis = 1, inplace = True)
df.head()

,BPHIGH4,BPMEDS,SEX,TOLDHI2,CVDINFR4,CVDSTRK3,DIABETE3,SMOKE100,SMOKDAY2,DRNK3GE5,_AGE80,_FRUTSUM,_VEGESUM,_PA150R2,_RACEGR3,height,weight
0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,1.0,3.0,NaN,63.0,50.0,217.0,3.0,1.0,70.0,280.0
1,3.0,NaN,2.0,2.0,2.0,2.0,3.0,1.0,1.0,NaN,52.0,24.0,78.0,1.0,1.0,68.0,165.0
2,3.0,NaN,2.0,1.0,7.0,1.0,3.0,NaN,NaN,NaN,71.0,NaN,NaN,9.0,1.0,71.0,158.0
3,1.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,NaN,NaN,63.0,100.0,20.0,3.0,1.0,67.0,180.0
4,3.0,NaN,2.0,2.0,2.0,2.0,3.0,2.0,NaN,NaN,61.0,NaN,200.0,3.0,1.0,64.0,142.0

In [14]:
df.rename({"_AGE80": "age", "CVDINFR4": "heart_attack", "CVDSTRK3": "stroke", "BPHIGH4": "high_bp", "BPMEDS": "bp_meds", "TOLDHI2": "high_chol", "_RACEGR3": "race"}, axis = 1, inplace = True)
df.head()

,high_bp,bp_meds,SEX,high_chol,heart_attack,stroke,DIABETE3,SMOKE100,SMOKDAY2,DRNK3GE5,age,_FRUTSUM,_VEGESUM,_PA150R2,race,height,weight
0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,1.0,3.0,NaN,63.0,50.0,217.0,3.0,1.0,70.0,280.0
1,3.0,NaN,2.0,2.0,2.0,2.0,3.0,1.0,1.0,NaN,52.0,24.0,78.0,1.0,1.0,68.0,165.0
2,3.0,NaN,2.0,1.0,7.0,1.0,3.0,NaN,NaN,NaN,71.0,NaN,NaN,9.0,1.0,71.0,158.0
3,1.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,NaN,NaN,63.0,100.0,20.0,3.0,1.0,67.0,180.0
4,3.0,NaN,2.0,2.0,2.0,2.0,3.0,2.0,NaN,NaN,61.0,NaN,200.0,3.0,1.0,64.0,142.0

In [15]:
df.rename({"DIABETE3": 'diabetes', "SEX": "sex", "SMOKE100": "smoke_100", "SMOKDAY2": "smoke_freq", "DRNK3GE5": 'drinking', "_FRUTSUM": "daily_fruit", "_VEGESUM": "daily_veg", "_PA150R2": "weekly_phys"}, inplace = True, axis = 1)
df.head()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight
0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,1.0,3.0,NaN,63.0,50.0,217.0,3.0,1.0,70.0,280.0
1,3.0,NaN,2.0,2.0,2.0,2.0,3.0,1.0,1.0,NaN,52.0,24.0,78.0,1.0,1.0,68.0,165.0
2,3.0,NaN,2.0,1.0,7.0,1.0,3.0,NaN,NaN,NaN,71.0,NaN,NaN,9.0,1.0,71.0,158.0
3,1.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,NaN,NaN,63.0,100.0,20.0,3.0,1.0,67.0,180.0
4,3.0,NaN,2.0,2.0,2.0,2.0,3.0,2.0,NaN,NaN,61.0,NaN,200.0,3.0,1.0,64.0,142.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 413000 entries, 0 to 441455
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   high_bp       412999 non-null  float64
 1   bp_meds       166838 non-null  float64
 2   sex           413000 non-null  float64
 3   high_chol     358034 non-null  float64
 4   heart_attack  413000 non-null  float64
 5   stroke        413000 non-null  float64
 6   diabetes      412993 non-null  float64
 7   smoke_100     400846 non-null  float64
 8   smoke_freq    175276 non-null  float64
 9   drinking      201379 non-null  float64
 10  age           413000 non-null  float64
 11  daily_fruit   375570 non-null  float64
 12  daily_veg     368937 non-null  float64
 13  weekly_phys   413000 non-null  float64
 14  race          413000 non-null  float64
 15  height        407369 non-null  float64
 16  weight        407685 non-null  float64
dtypes: float64(17)
memory usage: 56.7 MB

In [17]:
df.describe()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight
count,412999.000000,166838.000000,413000.000000,358034.000000,413000.000000,413000.000000,412993.000000,400846.000000,175276.000000,201379.000000,413000.000000,3.755700e+05,3.689370e+05,413000.000000,413000.000000,407369.000000,407685.000000
mean,2.206155,1.173641,1.560460,1.623659,1.965128,1.971663,2.756938,1.598976,2.432849,67.468837,55.433254,1.361374e+02,1.943727e+02,2.546293,1.652012,68.436334,178.278098
std,1.027882,0.445738,0.496332,0.718881,0.426887,0.334988,0.714990,0.701376,0.881476,36.053693,17.132764,1.375521e+02,1.549042e+02,2.409574,1.472622,25.483067,48.322973
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,18.000000,5.397605e-79,5.397605e-79,1.000000,1.000000,28.000000,-3136.818182
25%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,1.000000,2.000000,77.000000,43.000000,5.700000e+01,1.100000e+02,1.000000,1.000000,64.000000,145.000000
50%,3.000000,1.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,88.000000,58.000000,1.000000e+02,1.680000e+02,2.000000,1.000000,67.000000,171.000000
75%,3.000000,1.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,88.000000,69.000000,2.000000e+02,2.430000e+02,3.000000,1.000000,70.000000,200.000000
max,9.000000,9.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,99.000000,80.000000,1.500000e+04,1.992900e+04,9.000000,9.000000,468.110236,999.000000

In [18]:
df = df[df["height"] <= 96]
df = df[df["weight"] <= 998]
df.describe()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight
count,405640.000000,164478.000000,405641.000000,352383.000000,405641.000000,405641.000000,405634.000000,399161.00000,174795.000000,200739.000000,405641.000000,3.740290e+05,3.674280e+05,405641.000000,405641.000000,405641.000000,405641.000000
mean,2.203086,1.173215,1.560683,1.622050,1.964547,1.971396,2.756298,1.59837,2.432924,67.496037,55.514975,1.360990e+02,1.943054e+02,2.455159,1.633358,66.795923,178.489408
std,1.027975,0.444115,0.496305,0.717105,0.425349,0.334072,0.715392,0.70169,0.881481,36.036450,17.108782,1.375879e+02,1.548820e+02,2.301587,1.451341,4.148139,47.849259
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,18.000000,5.397605e-79,5.397605e-79,1.000000,1.000000,28.000000,15.454545
25%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,1.00000,2.000000,77.000000,43.000000,5.700000e+01,1.100000e+02,1.000000,1.000000,64.000000,145.000000
50%,3.000000,1.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.00000,3.000000,88.000000,58.000000,1.000000e+02,1.680000e+02,2.000000,1.000000,67.000000,172.000000
75%,3.000000,1.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.00000,3.000000,88.000000,69.000000,2.000000e+02,2.430000e+02,3.000000,1.000000,70.000000,200.000000
max,9.000000,9.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.00000,9.000000,99.000000,80.000000,1.500000e+04,1.992900e+04,9.000000,9.000000,95.000000,972.000000

In [19]:
df["smoke_freq"].fillna(3, inplace = True)
df["bp_meds"].fillna(2, inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 405641 entries, 0 to 441455
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   high_bp       405640 non-null  float64
 1   bp_meds       405641 non-null  float64
 2   sex           405641 non-null  float64
 3   high_chol     352383 non-null  float64
 4   heart_attack  405641 non-null  float64
 5   stroke        405641 non-null  float64
 6   diabetes      405634 non-null  float64
 7   smoke_100     399161 non-null  float64
 8   smoke_freq    405641 non-null  float64
 9   drinking      200739 non-null  float64
 10  age           405641 non-null  float64
 11  daily_fruit   374029 non-null  float64
 12  daily_veg     367428 non-null  float64
 13  weekly_phys   405641 non-null  float64
 14  race          405641 non-null  float64
 15  height        405641 non-null  float64
 16  weight        405641 non-null  float64
dtypes: float64(17)
memory usage: 55.7 MB

In [20]:
df["drinking"].fillna(88, inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 405641 entries, 0 to 441455
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   high_bp       405640 non-null  float64
 1   bp_meds       405641 non-null  float64
 2   sex           405641 non-null  float64
 3   high_chol     352383 non-null  float64
 4   heart_attack  405641 non-null  float64
 5   stroke        405641 non-null  float64
 6   diabetes      405634 non-null  float64
 7   smoke_100     399161 non-null  float64
 8   smoke_freq    405641 non-null  float64
 9   drinking      405641 non-null  float64
 10  age           405641 non-null  float64
 11  daily_fruit   374029 non-null  float64
 12  daily_veg     367428 non-null  float64
 13  weekly_phys   405641 non-null  float64
 14  race          405641 non-null  float64
 15  height        405641 non-null  float64
 16  weight        405641 non-null  float64
dtypes: float64(17)
memory usage: 55.7 MB

In [21]:
df.dropna(inplace = True)

In [22]:
df["BMI"] = df["weight"] / 2.2 / (df["height"] * 0.0254) ** 2
df.head()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight,BMI
0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,1.0,3.0,88.0,63.0,50.0,217.0,3.0,1.0,70.0,280.0,40.259821
1,3.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,1.0,88.0,52.0,24.0,78.0,1.0,1.0,68.0,165.0,25.140621
3,1.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,3.0,88.0,63.0,100.0,20.0,3.0,1.0,67.0,180.0,28.250932
5,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,88.0,73.0,200.0,600.0,1.0,1.0,62.0,145.0,26.576299
6,1.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,3.0,88.0,70.0,129.0,114.0,1.0,4.0,66.0,148.0,23.937772

In [23]:
df["drinking"].replace({88: 0}, inplace = True)
df = df[df["high_bp"] // 6.0 < 1]
df = df[df["high_chol"] // 6.0 < 1]
df = df[df["smoke_100"] // 6.0 < 1]
df = df[df["smoke_freq"] // 6.0 < 1]
df = df[df["heart_attack"] // 6.0 < 1]
df = df[df["stroke"] // 6.0 < 1]
df = df[df["diabetes"] // 6.0 < 1]
df = df[df["weekly_phys"] // 6.0 < 1]
df["daily_veg"] = df["daily_veg"] / 100
df["daily_fruit"] = df["daily_fruit"] / 100
df.describe()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight,BMI
count,298488.000000,298488.000000,298488.000000,298488.000000,298488.000000,298488.000000,298488.000000,298488.000000,298488.000000,298488.000000,298488.000000,2.984880e+05,2.984880e+05,298488.000000,298488.000000,298488.000000,298488.000000,298488.000000
mean,2.134213,1.631975,1.573856,1.573621,1.936986,1.957171,2.727768,1.558696,2.772038,0.832881,57.590111,1.380992e+00,1.980018e+00,1.720029,1.554146,66.768795,179.983431,28.332282
std,1.003771,0.498898,0.494516,0.494551,0.242989,0.202472,0.720278,0.496544,0.604038,5.921304,15.381285,1.308576e+00,1.562150e+00,0.860495,1.356042,4.099107,47.577796,6.675012
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,18.000000,5.397605e-81,5.397605e-81,1.000000,1.000000,28.000000,15.454545,3.012282
25%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,1.000000,3.000000,0.000000,47.000000,5.700000e-01,1.140000e+00,1.000000,1.000000,64.000000,148.000000,24.081192
50%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,0.000000,60.000000,1.030000e+00,1.710000e+00,1.000000,1.000000,66.000000,175.000000,27.319164
75%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,0.000000,69.000000,2.000000e+00,2.490000e+00,3.000000,1.000000,70.000000,200.000000,31.258831
max,4.000000,9.000000,2.000000,2.000000,2.000000,2.000000,4.000000,2.000000,3.000000,99.000000,80.000000,1.500000e+02,1.992900e+02,3.000000,9.000000,91.000000,700.000000,337.894924

In [24]:
df = df[df["daily_veg"]  < 20]
df = df[df["daily_fruit"] < 20]
df = df[df["bp_meds"] // 6.0 < 1]
df.describe()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight,BMI
count,298257.000000,298257.000000,298257.000000,298257.000000,298257.000000,298257.000000,298257.000000,298257.000000,298257.000000,298257.000000,298257.000000,2.982570e+05,2.982570e+05,298257.000000,298257.000000,298257.000000,298257.000000,298257.000000
mean,2.134766,1.629236,1.573881,1.573720,1.937061,1.957205,2.727859,1.558740,2.772052,0.832835,57.585012,1.373694e+00,1.972514e+00,1.719953,1.554059,66.768783,179.983097,28.332244
std,1.003698,0.483010,0.494512,0.494536,0.242854,0.202396,0.720156,0.496539,0.604019,5.920526,15.380934,1.131302e+00,1.326935e+00,0.860465,1.355721,4.098965,47.579376,6.675404
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,18.000000,5.397605e-81,5.397605e-81,1.000000,1.000000,28.000000,15.454545,3.012282
25%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,1.000000,3.000000,0.000000,47.000000,5.700000e-01,1.140000e+00,1.000000,1.000000,64.000000,148.000000,24.081192
50%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,0.000000,60.000000,1.030000e+00,1.710000e+00,1.000000,1.000000,66.000000,175.000000,27.319164
75%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,0.000000,69.000000,2.000000e+00,2.490000e+00,3.000000,1.000000,70.000000,200.000000,31.258831
max,4.000000,2.000000,2.000000,2.000000,2.000000,2.000000,4.000000,2.000000,3.000000,99.000000,80.000000,1.900000e+01,1.950000e+01,3.000000,9.000000,91.000000,700.000000,337.894924

In [25]:
df = df[df["drinking"] <= 30]

In [26]:
df.describe()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight,BMI
count,296929.000000,296929.000000,296929.000000,296929.000000,296929.000000,296929.000000,296929.000000,296929.000000,296929.000000,296929.000000,296929.000000,2.969290e+05,2.969290e+05,296929.000000,296929.000000,296929.000000,296929.000000,296929.000000
mean,2.134733,1.629137,1.574363,1.573504,1.937069,1.957188,2.727396,1.559676,2.773346,0.473511,57.593044,1.374181e+00,1.972961e+00,1.719488,1.552944,66.767092,179.995528,28.335523
std,1.003671,0.483037,0.494440,0.494568,0.242839,0.202432,0.720549,0.496427,0.602510,2.407990,15.381279,1.130886e+00,1.326741e+00,0.860223,1.354355,4.098374,47.576675,6.674342
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,18.000000,5.397605e-81,5.397605e-81,1.000000,1.000000,28.000000,15.454545,3.012282
25%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,1.000000,3.000000,0.000000,47.000000,5.700000e-01,1.140000e+00,1.000000,1.000000,64.000000,148.000000,24.081192
50%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,0.000000,60.000000,1.030000e+00,1.710000e+00,1.000000,1.000000,66.000000,175.000000,27.319164
75%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,0.000000,69.000000,2.000000e+00,2.490000e+00,3.000000,1.000000,70.000000,200.000000,31.258831
max,4.000000,2.000000,2.000000,2.000000,2.000000,2.000000,4.000000,2.000000,3.000000,30.000000,80.000000,1.900000e+01,1.950000e+01,3.000000,9.000000,91.000000,700.000000,337.894924

In [27]:
df = df[df["BMI"] < 200]

In [28]:
df.describe()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight,BMI
count,296927.000000,296927.000000,296927.000000,296927.000000,296927.000000,296927.000000,296927.000000,296927.000000,296927.000000,296927.000000,296927.000000,2.969270e+05,2.969270e+05,296927.000000,296927.000000,296927.000000,296927.000000,296927.000000
mean,2.134733,1.629138,1.574360,1.573501,1.937069,1.957188,2.727401,1.559673,2.773345,0.473514,57.593041,1.374188e+00,1.972965e+00,1.719487,1.552947,66.767347,179.994532,28.333837
std,1.003671,0.483036,0.494441,0.494569,0.242840,0.202433,0.720544,0.496427,0.602512,2.407998,15.381330,1.130886e+00,1.326744e+00,0.860221,1.354358,4.097215,47.575121,6.640913
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,18.000000,5.397605e-81,5.397605e-81,1.000000,1.000000,32.000000,15.454545,3.012282
25%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,1.000000,3.000000,0.000000,47.000000,5.700000e-01,1.140000e+00,1.000000,1.000000,64.000000,148.000000,24.081192
50%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,0.000000,60.000000,1.030000e+00,1.710000e+00,1.000000,1.000000,66.000000,175.000000,27.319164
75%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,0.000000,69.000000,2.000000e+00,2.490000e+00,3.000000,1.000000,70.000000,200.000000,31.258831
max,4.000000,2.000000,2.000000,2.000000,2.000000,2.000000,4.000000,2.000000,3.000000,30.000000,80.000000,1.900000e+01,1.950000e+01,3.000000,9.000000,91.000000,700.000000,182.329022

In [29]:
df.head()

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight,BMI
0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,1.0,3.0,0.0,63.0,0.50,2.17,3.0,1.0,70.0,280.0,40.259821
1,3.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,1.0,0.0,52.0,0.24,0.78,1.0,1.0,68.0,165.0,25.140621
3,1.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,3.0,0.0,63.0,1.00,0.20,3.0,1.0,67.0,180.0,28.250932
5,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,0.0,73.0,2.00,6.00,1.0,1.0,62.0,145.0,26.576299
6,1.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,3.0,0.0,70.0,1.29,1.14,1.0,4.0,66.0,148.0,23.937772

In [93]:
df["stroke"].replace({2: 0}, inplace = True)
df["heart_attack"].replace({2: 0}, inplace = True)
df["diabetes"].replace({2: 1, 4: 1, 3: 0}, inplace = True)

In [94]:
test_model(2, [32, 32, 32], [1, 1, 1, 1], "stroke", 5)

Epoch 1/20
928/928 [==============================] - 1s 645us/step - loss: 0.6734 - acc: 0.9369
Epoch 2/20
928/928 [==============================] - 1s 623us/step - loss: 0.3324 - acc: 0.9495
Epoch 3/20
928/928 [==============================] - 1s 630us/step - loss: 0.2551 - acc: 0.9539
Epoch 4/20
928/928 [==============================] - 1s 583us/step - loss: 0.2228 - acc: 0.9554
Epoch 5/20
928/928 [==============================] - 1s 629us/step - loss: 0.1970 - acc: 0.9569
Epoch 6/20
928/928 [==============================] - 1s 611us/step - loss: 0.1883 - acc: 0.9571
Epoch 7/20
928/928 [==============================] - 1s 718us/step - loss: 0.1818 - acc: 0.9571
Epoch 8/20
928/928 [==============================] - 1s 647us/step - loss: 0.1783 - acc: 0.9573
Epoch 9/20
928/928 [==============================] - 1s 595us/step - loss: 0.1775 - acc: 0.9572
Epoch 10/20
928/928 [==============================] - 1s 589us/step - loss: 0.1748 - acc: 0.9573
Epoch 11/20
928/928 [==============================] - 1s 589us/step - loss: 0.1719 - acc: 0.9573
Epoch 12/20
928/928 [==============================] - 1s 592us/step - loss: 0.1721 - acc: 0.9573
Epoch 13/20
928/928 [==============================] - 1s 595us/step - loss: 0.1705 - acc: 0.9574
Epoch 14/20
928/928 [==============================] - 1s 595us/step - loss: 0.1695 - acc: 0.9574
Epoch 15/20
928/928 [==============================] - 1s 586us/step - loss: 0.1683 - acc: 0.9574
Epoch 16/20
928/928 [==============================] - 1s 595us/step - loss: 0.1674 - acc: 0.9574
Epoch 17/20
928/928 [==============================] - 1s 587us/step - loss: 0.1678 - acc: 0.9574
Epoch 18/20
928/928 [==============================] - 1s 588us/step - loss: 0.1658 - acc: 0.9574
Epoch 19/20
928/928 [==============================] - 1s 592us/step - loss: 0.1657 - acc: 0.9574
Epoch 20/20
928/928 [==============================] - 1s 602us/step - loss: 0.1657 - acc: 0.9574
1856/1856 [==============================] - 1s 418us/step
Epoch 1/20
696/696 [==============================] - 0s 604us/step - loss: 0.1640 - acc: 0.9577
Epoch 2/20
696/696 [==============================] - 0s 607us/step - loss: 0.1637 - acc: 0.9577
Epoch 3/20
696/696 [==============================] - 0s 588us/step - loss: 0.1645 - acc: 0.9577
Epoch 4/20
696/696 [==============================] - 0s 603us/step - loss: 0.1635 - acc: 0.9577
Epoch 5/20
696/696 [==============================] - 0s 606us/step - loss: 0.1634 - acc: 0.9577
Epoch 6/20
696/696 [==============================] - 0s 585us/step - loss: 0.1628 - acc: 0.9577
Epoch 7/20
696/696 [==============================] - 0s 603us/step - loss: 0.1634 - acc: 0.9577
Epoch 8/20
696/696 [==============================] - 0s 601us/step - loss: 0.1625 - acc: 0.9577
Epoch 9/20
696/696 [==============================] - 1s 740us/step - loss: 0.1627 - acc: 0.9577
Epoch 10/20
696/696 [==============================] - 1s 718us/step - loss: 0.1619 - acc: 0.9577
Epoch 11/20
696/696 [==============================] - 0s 639us/step - loss: 0.1624 - acc: 0.9577
Epoch 12/20
696/696 [==============================] - 0s 587us/step - loss: 0.1619 - acc: 0.9577
Epoch 13/20
696/696 [==============================] - 0s 600us/step - loss: 0.1616 - acc: 0.9577
Epoch 14/20
696/696 [==============================] - 0s 591us/step - loss: 0.1627 - acc: 0.9577
Epoch 15/20
696/696 [==============================] - 0s 598us/step - loss: 0.1621 - acc: 0.9577
Epoch 16/20
696/696 [==============================] - 0s 603us/step - loss: 0.1612 - acc: 0.9577
Epoch 17/20
696/696 [==============================] - 0s 577us/step - loss: 0.1615 - acc: 0.9577
Epoch 18/20
696/696 [==============================] - 0s 586us/step - loss: 0.1619 - acc: 0.9577
Epoch 19/20
696/696 [==============================] - 0s 599us/step - loss: 0.1620 - acc: 0.9577
Epoch 20/20
696/696 [==============================] - 0s 579us/step - loss: 0.1612 - acc: 0.9577
1856/1856 [==============================] - 1s 404us/step
Epoch 1/20
464/464 [==============================] - 0s 593us/step - loss: 0.1623 - acc: 0.9573
Epoch 2/20
464/464 [==============================] - 0s 586us/step - loss: 0.1622 - acc: 0.9573
Epoch 3/20
464/464 [==============================] - 0s 587us/step - loss: 0.1624 - acc: 0.9573
Epoch 4/20
464/464 [==============================] - 0s 588us/step - loss: 0.1624 - acc: 0.9573
Epoch 5/20
464/464 [==============================] - 0s 584us/step - loss: 0.1618 - acc: 0.9573
Epoch 6/20
464/464 [==============================] - 0s 607us/step - loss: 0.1620 - acc: 0.9573
Epoch 7/20
464/464 [==============================] - 0s 597us/step - loss: 0.1618 - acc: 0.9573
Epoch 8/20
464/464 [==============================] - 0s 581us/step - loss: 0.1618 - acc: 0.9573
Epoch 9/20
464/464 [==============================] - 0s 581us/step - loss: 0.1618 - acc: 0.9573
Epoch 10/20
464/464 [==============================] - 0s 581us/step - loss: 0.1619 - acc: 0.9573
Epoch 11/20
464/464 [==============================] - 0s 587us/step - loss: 0.1623 - acc: 0.9573
Epoch 12/20
464/464 [==============================] - 0s 585us/step - loss: 0.1618 - acc: 0.9573
Epoch 13/20
464/464 [==============================] - 0s 584us/step - loss: 0.1614 - acc: 0.9573
Epoch 14/20
464/464 [==============================] - 0s 582us/step - loss: 0.1615 - acc: 0.9573
Epoch 15/20
464/464 [==============================] - 0s 583us/step - loss: 0.1615 - acc: 0.9573
Epoch 16/20
464/464 [==============================] - 0s 599us/step - loss: 0.1612 - acc: 0.9573
Epoch 17/20
464/464 [==============================] - 0s 678us/step - loss: 0.1620 - acc: 0.9573
Epoch 18/20
464/464 [==============================] - 0s 601us/step - loss: 0.1614 - acc: 0.9573
Epoch 19/20
464/464 [==============================] - 0s 588us/step - loss: 0.1611 - acc: 0.9573
Epoch 20/20
464/464 [==============================] - 0s 612us/step - loss: 0.1616 - acc: 0.9573
1856/1856 [==============================] - 1s 445us/step
Epoch 1/20
232/232 [==============================] - 0s 800us/step - loss: 0.1594 - acc: 0.9579
Epoch 2/20
232/232 [==============================] - 0s 688us/step - loss: 0.1601 - acc: 0.9579
Epoch 3/20
232/232 [==============================] - 0s 646us/step - loss: 0.1607 - acc: 0.9579
Epoch 4/20
232/232 [==============================] - 0s 603us/step - loss: 0.1598 - acc: 0.9579
Epoch 5/20
232/232 [==============================] - 0s 628us/step - loss: 0.1596 - acc: 0.9579
Epoch 6/20
232/232 [==============================] - 0s 580us/step - loss: 0.1598 - acc: 0.9579
Epoch 7/20
232/232 [==============================] - 0s 626us/step - loss: 0.1591 - acc: 0.9579
Epoch 8/20
232/232 [==============================] - 0s 586us/step - loss: 0.1596 - acc: 0.9579
Epoch 9/20
232/232 [==============================] - 0s 652us/step - loss: 0.1593 - acc: 0.9579
Epoch 10/20
232/232 [==============================] - 0s 628us/step - loss: 0.1596 - acc: 0.9579
Epoch 11/20
232/232 [==============================] - 0s 639us/step - loss: 0.1592 - acc: 0.9579
Epoch 12/20
232/232 [==============================] - 0s 663us/step - loss: 0.1590 - acc: 0.9579
Epoch 13/20
232/232 [==============================] - 0s 611us/step - loss: 0.1591 - acc: 0.9579
Epoch 14/20
232/232 [==============================] - 0s 642us/step - loss: 0.1606 - acc: 0.9579
Epoch 15/20
232/232 [==============================] - 0s 610us/step - loss: 0.1591 - acc: 0.9579
Epoch 16/20
232/232 [==============================] - 0s 584us/step - loss: 0.1597 - acc: 0.9580
Epoch 17/20
232/232 [==============================] - 0s 620us/step - loss: 0.1591 - acc: 0.9579
Epoch 18/20
232/232 [==============================] - 0s 589us/step - loss: 0.1595 - acc: 0.9579
Epoch 19/20
232/232 [==============================] - 0s 631us/step - loss: 0.1591 - acc: 0.9579
Epoch 20/20
232/232 [==============================] - 0s 571us/step - loss: 0.1596 - acc: 0.9579
1856/1856 [==============================] - 1s 413us/step
Epoch 1/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0528 - acc: 1.0000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0156 - acc: 1.0000
Epoch 3/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0108 - acc: 1.0000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0083 - acc: 1.0000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0068 - acc: 1.0000
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0058 - acc: 1.0000
Epoch 7/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 8/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0045 - acc: 1.0000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0040 - acc: 1.0000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0036 - acc: 1.0000
Epoch 11/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0033 - acc: 1.0000
Epoch 12/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0031 - acc: 1.0000
Epoch 13/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0029 - acc: 1.0000
Epoch 14/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0027 - acc: 1.0000
Epoch 15/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0025 - acc: 1.0000
Epoch 16/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0024 - acc: 1.0000
Epoch 17/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 18/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0021 - acc: 1.0000
Epoch 19/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0020 - acc: 1.0000
Epoch 20/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0019 - acc: 1.0000
1856/1856 [==============================] - 1s 436us/step

array([0.95643681, 0.95650417, 0.9585754 , 0.95672308, 0.95793551])

In [46]:
test_model(2, [32, 32, 32], [1, 1, 1, 1], "heart_attack", 5)

Epoch 1/20
928/928 [==============================] - 1s 568us/step - loss: 1.0702 - acc: 0.9009
Epoch 2/20
928/928 [==============================] - 1s 558us/step - loss: 0.3516 - acc: 0.9272
Epoch 3/20
928/928 [==============================] - 1s 556us/step - loss: 0.2655 - acc: 0.9335
Epoch 4/20
928/928 [==============================] - 1s 553us/step - loss: 0.2419 - acc: 0.9352
Epoch 5/20
928/928 [==============================] - 1s 553us/step - loss: 0.2339 - acc: 0.9355
Epoch 6/20
928/928 [==============================] - 1s 549us/step - loss: 0.2287 - acc: 0.9359
Epoch 7/20
928/928 [==============================] - 1s 555us/step - loss: 0.2237 - acc: 0.9361
Epoch 8/20
928/928 [==============================] - 1s 551us/step - loss: 0.2201 - acc: 0.9362
Epoch 9/20
928/928 [==============================] - 1s 551us/step - loss: 0.2182 - acc: 0.9362
Epoch 10/20
928/928 [==============================] - 1s 555us/step - loss: 0.2171 - acc: 0.9363
Epoch 11/20
928/928 [==============================] - 1s 665us/step - loss: 0.2153 - acc: 0.9364
Epoch 12/20
928/928 [==============================] - 1s 631us/step - loss: 0.2155 - acc: 0.9364
Epoch 13/20
928/928 [==============================] - 1s 612us/step - loss: 0.2134 - acc: 0.9364
Epoch 14/20
928/928 [==============================] - 1s 557us/step - loss: 0.2119 - acc: 0.9365
Epoch 15/20
928/928 [==============================] - 1s 558us/step - loss: 0.2118 - acc: 0.9365
Epoch 16/20
928/928 [==============================] - 1s 548us/step - loss: 0.2114 - acc: 0.9366
Epoch 17/20
928/928 [==============================] - 1s 547us/step - loss: 0.2106 - acc: 0.9365
Epoch 18/20
928/928 [==============================] - 1s 546us/step - loss: 0.2107 - acc: 0.9365
Epoch 19/20
928/928 [==============================] - 1s 548us/step - loss: 0.2093 - acc: 0.9365
Epoch 20/20
928/928 [==============================] - 1s 550us/step - loss: 0.2097 - acc: 0.9366
1856/1856 [==============================] - 1s 375us/step
Epoch 1/20
696/696 [==============================] - 0s 606us/step - loss: 0.2095 - acc: 0.9367
Epoch 2/20
696/696 [==============================] - 0s 566us/step - loss: 0.2088 - acc: 0.9367
Epoch 3/20
696/696 [==============================] - 0s 558us/step - loss: 0.2084 - acc: 0.9368
Epoch 4/20
696/696 [==============================] - 0s 562us/step - loss: 0.2083 - acc: 0.9368
Epoch 5/20
696/696 [==============================] - 0s 556us/step - loss: 0.2080 - acc: 0.9368
Epoch 6/20
696/696 [==============================] - 0s 556us/step - loss: 0.2082 - acc: 0.9368
Epoch 7/20
696/696 [==============================] - 0s 558us/step - loss: 0.2078 - acc: 0.9368
Epoch 8/20
696/696 [==============================] - 0s 562us/step - loss: 0.2074 - acc: 0.9368
Epoch 9/20
696/696 [==============================] - 0s 553us/step - loss: 0.2078 - acc: 0.9368
Epoch 10/20
696/696 [==============================] - 0s 556us/step - loss: 0.2073 - acc: 0.9368
Epoch 11/20
696/696 [==============================] - 0s 554us/step - loss: 0.2072 - acc: 0.9368
Epoch 12/20
696/696 [==============================] - 0s 559us/step - loss: 0.2071 - acc: 0.9368
Epoch 13/20
696/696 [==============================] - 0s 557us/step - loss: 0.2070 - acc: 0.9368
Epoch 14/20
696/696 [==============================] - 0s 558us/step - loss: 0.2072 - acc: 0.9368
Epoch 15/20
696/696 [==============================] - 0s 557us/step - loss: 0.2075 - acc: 0.9368
Epoch 16/20
696/696 [==============================] - 0s 622us/step - loss: 0.2065 - acc: 0.9369
Epoch 17/20
696/696 [==============================] - 1s 746us/step - loss: 0.2061 - acc: 0.9368
Epoch 18/20
696/696 [==============================] - 0s 683us/step - loss: 0.2066 - acc: 0.9369
Epoch 19/20
696/696 [==============================] - 0s 594us/step - loss: 0.2068 - acc: 0.9368
Epoch 20/20
696/696 [==============================] - 0s 560us/step - loss: 0.2071 - acc: 0.9367
1856/1856 [==============================] - 1s 377us/step
Epoch 1/20
464/464 [==============================] - 0s 569us/step - loss: 0.2047 - acc: 0.9373
Epoch 2/20
464/464 [==============================] - 0s 566us/step - loss: 0.2049 - acc: 0.9373
Epoch 3/20
464/464 [==============================] - 0s 559us/step - loss: 0.2045 - acc: 0.9372
Epoch 4/20
464/464 [==============================] - 0s 562us/step - loss: 0.2045 - acc: 0.9372
Epoch 5/20
464/464 [==============================] - 0s 572us/step - loss: 0.2042 - acc: 0.9373
Epoch 6/20
464/464 [==============================] - 0s 568us/step - loss: 0.2052 - acc: 0.9372
Epoch 7/20
464/464 [==============================] - 0s 562us/step - loss: 0.2043 - acc: 0.9372
Epoch 8/20
464/464 [==============================] - 0s 556us/step - loss: 0.2044 - acc: 0.9373
Epoch 9/20
464/464 [==============================] - 0s 562us/step - loss: 0.2037 - acc: 0.9373
Epoch 10/20
464/464 [==============================] - 0s 568us/step - loss: 0.2047 - acc: 0.9373
Epoch 11/20
464/464 [==============================] - 0s 559us/step - loss: 0.2040 - acc: 0.9372
Epoch 12/20
464/464 [==============================] - 0s 561us/step - loss: 0.2046 - acc: 0.9373
Epoch 13/20
464/464 [==============================] - 0s 558us/step - loss: 0.2039 - acc: 0.9372
Epoch 14/20
464/464 [==============================] - 0s 563us/step - loss: 0.2039 - acc: 0.9373
Epoch 15/20
464/464 [==============================] - 0s 568us/step - loss: 0.2042 - acc: 0.9373
Epoch 16/20
464/464 [==============================] - 0s 565us/step - loss: 0.2042 - acc: 0.9372
Epoch 17/20
464/464 [==============================] - 0s 571us/step - loss: 0.2041 - acc: 0.9372
Epoch 18/20
464/464 [==============================] - 0s 561us/step - loss: 0.2038 - acc: 0.9372
Epoch 19/20
464/464 [==============================] - 0s 564us/step - loss: 0.2039 - acc: 0.9372
Epoch 20/20
464/464 [==============================] - 0s 564us/step - loss: 0.2044 - acc: 0.9372
1856/1856 [==============================] - 1s 379us/step
Epoch 1/20
232/232 [==============================] - 0s 582us/step - loss: 0.2054 - acc: 0.9366
Epoch 2/20
232/232 [==============================] - 0s 567us/step - loss: 0.2054 - acc: 0.9365
Epoch 3/20
232/232 [==============================] - 0s 575us/step - loss: 0.2054 - acc: 0.9366
Epoch 4/20
232/232 [==============================] - 0s 569us/step - loss: 0.2049 - acc: 0.9366
Epoch 5/20
232/232 [==============================] - 0s 573us/step - loss: 0.2060 - acc: 0.9366
Epoch 6/20
232/232 [==============================] - 0s 568us/step - loss: 0.2054 - acc: 0.9365
Epoch 7/20
232/232 [==============================] - 0s 569us/step - loss: 0.2055 - acc: 0.9366
Epoch 8/20
232/232 [==============================] - 0s 564us/step - loss: 0.2053 - acc: 0.9364
Epoch 9/20
232/232 [==============================] - 0s 568us/step - loss: 0.2055 - acc: 0.9366
Epoch 10/20
232/232 [==============================] - 0s 581us/step - loss: 0.2050 - acc: 0.9366
Epoch 11/20
232/232 [==============================] - 0s 574us/step - loss: 0.2054 - acc: 0.9364
Epoch 12/20
232/232 [==============================] - 0s 579us/step - loss: 0.2055 - acc: 0.9365
Epoch 13/20
232/232 [==============================] - 0s 563us/step - loss: 0.2053 - acc: 0.9366
Epoch 14/20
232/232 [==============================] - 0s 573us/step - loss: 0.2050 - acc: 0.9365
Epoch 15/20
232/232 [==============================] - 0s 571us/step - loss: 0.2051 - acc: 0.9366
Epoch 16/20
232/232 [==============================] - 0s 575us/step - loss: 0.2052 - acc: 0.9367
Epoch 17/20
232/232 [==============================] - 0s 573us/step - loss: 0.2054 - acc: 0.9365
Epoch 18/20
232/232 [==============================] - 0s 568us/step - loss: 0.2062 - acc: 0.9366
Epoch 19/20
232/232 [==============================] - 0s 565us/step - loss: 0.2052 - acc: 0.9365
Epoch 20/20
232/232 [==============================] - 0s 561us/step - loss: 0.2048 - acc: 0.9364
1856/1856 [==============================] - 1s 374us/step
Epoch 1/20
1/1 [==============================] - 0s 3ms/step - loss: 0.2047 - acc: 1.0000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0148 - acc: 1.0000
Epoch 3/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0120 - acc: 1.0000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0101 - acc: 1.0000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0088 - acc: 1.0000
Epoch 6/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0078 - acc: 1.0000
Epoch 7/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0070 - acc: 1.0000
Epoch 8/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0063 - acc: 1.0000
Epoch 9/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0058 - acc: 1.0000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0053 - acc: 1.0000
Epoch 11/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0049 - acc: 1.0000
Epoch 12/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0046 - acc: 1.0000
Epoch 13/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0043 - acc: 1.0000
Epoch 14/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0041 - acc: 1.0000
Epoch 15/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0038 - acc: 1.0000
Epoch 16/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0036 - acc: 1.0000
Epoch 17/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0035 - acc: 1.0000
Epoch 18/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0033 - acc: 1.0000
Epoch 19/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0031 - acc: 1.0000
Epoch 20/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0030 - acc: 1.0000
1856/1856 [==============================] - 1s 381us/step

array([0.93752631, 0.93579187, 0.93580871, 0.93819988, 0.93673487])

In [95]:
test_model(2, [32, 32, 32], [1, 1, 1, 1], "diabetes", 5)

Epoch 1/20
928/928 [==============================] - 1s 633us/step - loss: 1.6931 - acc: 0.7726
Epoch 2/20
928/928 [==============================] - 1s 584us/step - loss: 0.4422 - acc: 0.8247
Epoch 3/20
928/928 [==============================] - 1s 583us/step - loss: 0.4140 - acc: 0.8298
Epoch 4/20
928/928 [==============================] - 1s 599us/step - loss: 0.4091 - acc: 0.8307
Epoch 5/20
928/928 [==============================] - 1s 621us/step - loss: 0.4049 - acc: 0.8310
Epoch 6/20
928/928 [==============================] - 1s 599us/step - loss: 0.4028 - acc: 0.8316
Epoch 7/20
928/928 [==============================] - 1s 585us/step - loss: 0.4012 - acc: 0.8316
Epoch 8/20
928/928 [==============================] - 1s 584us/step - loss: 0.3996 - acc: 0.8315
Epoch 9/20
928/928 [==============================] - 1s 581us/step - loss: 0.3987 - acc: 0.8316
Epoch 10/20
928/928 [==============================] - 1s 583us/step - loss: 0.3976 - acc: 0.8316
Epoch 11/20
928/928 [==============================] - 1s 708us/step - loss: 0.3968 - acc: 0.8317
Epoch 12/20
928/928 [==============================] - 1s 626us/step - loss: 0.3967 - acc: 0.8321
Epoch 13/20
928/928 [==============================] - 1s 603us/step - loss: 0.3957 - acc: 0.8321
Epoch 14/20
928/928 [==============================] - 1s 587us/step - loss: 0.3960 - acc: 0.8313
Epoch 15/20
928/928 [==============================] - 1s 590us/step - loss: 0.3956 - acc: 0.8319
Epoch 16/20
928/928 [==============================] - 1s 585us/step - loss: 0.3950 - acc: 0.8320
Epoch 17/20
928/928 [==============================] - 1s 585us/step - loss: 0.3952 - acc: 0.8316
Epoch 18/20
928/928 [==============================] - 1s 589us/step - loss: 0.3948 - acc: 0.8319
Epoch 19/20
928/928 [==============================] - 1s 630us/step - loss: 0.3940 - acc: 0.8323
Epoch 20/20
928/928 [==============================] - 1s 650us/step - loss: 0.3936 - acc: 0.8325
1856/1856 [==============================] - 1s 422us/step
Epoch 1/20
696/696 [==============================] - 0s 633us/step - loss: 0.3931 - acc: 0.8324
Epoch 2/20
696/696 [==============================] - 0s 616us/step - loss: 0.3939 - acc: 0.8325
Epoch 3/20
696/696 [==============================] - 0s 612us/step - loss: 0.3940 - acc: 0.8323
Epoch 4/20
696/696 [==============================] - 0s 664us/step - loss: 0.3925 - acc: 0.8328
Epoch 5/20
696/696 [==============================] - 0s 626us/step - loss: 0.3927 - acc: 0.8328
Epoch 6/20
696/696 [==============================] - 0s 621us/step - loss: 0.3923 - acc: 0.8330
Epoch 7/20
696/696 [==============================] - 0s 623us/step - loss: 0.3928 - acc: 0.8323
Epoch 8/20
696/696 [==============================] - 0s 626us/step - loss: 0.3923 - acc: 0.8328
Epoch 9/20
696/696 [==============================] - 0s 629us/step - loss: 0.3921 - acc: 0.8331
Epoch 10/20
696/696 [==============================] - 0s 585us/step - loss: 0.3925 - acc: 0.8327
Epoch 11/20
696/696 [==============================] - 0s 595us/step - loss: 0.3919 - acc: 0.8332
Epoch 12/20
696/696 [==============================] - 0s 595us/step - loss: 0.3918 - acc: 0.8331
Epoch 13/20
696/696 [==============================] - 0s 584us/step - loss: 0.3920 - acc: 0.8331
Epoch 14/20
696/696 [==============================] - 0s 600us/step - loss: 0.3916 - acc: 0.8332
Epoch 15/20
696/696 [==============================] - 0s 581us/step - loss: 0.3922 - acc: 0.8329
Epoch 16/20
696/696 [==============================] - 0s 584us/step - loss: 0.3923 - acc: 0.8330
Epoch 17/20
696/696 [==============================] - 0s 595us/step - loss: 0.3915 - acc: 0.8326
Epoch 18/20
696/696 [==============================] - 0s 583us/step - loss: 0.3912 - acc: 0.8329
Epoch 19/20
696/696 [==============================] - 0s 597us/step - loss: 0.3916 - acc: 0.8329
Epoch 20/20
696/696 [==============================] - 0s 597us/step - loss: 0.3912 - acc: 0.8332
1856/1856 [==============================] - 1s 401us/step
Epoch 1/20
464/464 [==============================] - 0s 609us/step - loss: 0.3920 - acc: 0.8324
Epoch 2/20
464/464 [==============================] - 0s 584us/step - loss: 0.3926 - acc: 0.8323
Epoch 3/20
464/464 [==============================] - 0s 572us/step - loss: 0.3924 - acc: 0.8320
Epoch 4/20
464/464 [==============================] - 0s 576us/step - loss: 0.3917 - acc: 0.8324
Epoch 5/20
464/464 [==============================] - 0s 645us/step - loss: 0.3931 - acc: 0.8318
Epoch 6/20
464/464 [==============================] - 0s 681us/step - loss: 0.3916 - acc: 0.8321
Epoch 7/20
464/464 [==============================] - 0s 577us/step - loss: 0.3921 - acc: 0.8319
Epoch 8/20
464/464 [==============================] - 0s 568us/step - loss: 0.3926 - acc: 0.8319
Epoch 9/20
464/464 [==============================] - 0s 576us/step - loss: 0.3920 - acc: 0.8322
Epoch 10/20
464/464 [==============================] - 0s 583us/step - loss: 0.3918 - acc: 0.8322
Epoch 11/20
464/464 [==============================] - 0s 579us/step - loss: 0.3915 - acc: 0.8323
Epoch 12/20
464/464 [==============================] - 0s 564us/step - loss: 0.3922 - acc: 0.8321
Epoch 13/20
464/464 [==============================] - 0s 575us/step - loss: 0.3913 - acc: 0.8324
Epoch 14/20
464/464 [==============================] - 0s 573us/step - loss: 0.3919 - acc: 0.8326
Epoch 15/20
464/464 [==============================] - 0s 579us/step - loss: 0.3916 - acc: 0.8324
Epoch 16/20
464/464 [==============================] - 0s 580us/step - loss: 0.3913 - acc: 0.8322
Epoch 17/20
464/464 [==============================] - 0s 574us/step - loss: 0.3915 - acc: 0.8325
Epoch 18/20
464/464 [==============================] - 0s 580us/step - loss: 0.3912 - acc: 0.8326
Epoch 19/20
464/464 [==============================] - 0s 572us/step - loss: 0.3920 - acc: 0.8322
Epoch 20/20
464/464 [==============================] - 0s 575us/step - loss: 0.3913 - acc: 0.8321
1856/1856 [==============================] - 1s 396us/step
Epoch 1/20
232/232 [==============================] - 0s 769us/step - loss: 0.3926 - acc: 0.8319
Epoch 2/20
232/232 [==============================] - 0s 738us/step - loss: 0.3934 - acc: 0.8315
Epoch 3/20
232/232 [==============================] - 0s 602us/step - loss: 0.3944 - acc: 0.8319
Epoch 4/20
232/232 [==============================] - 0s 669us/step - loss: 0.3928 - acc: 0.8312
Epoch 5/20
232/232 [==============================] - 0s 747us/step - loss: 0.3926 - acc: 0.8328
Epoch 6/20
232/232 [==============================] - 0s 712us/step - loss: 0.3932 - acc: 0.8317
Epoch 7/20
232/232 [==============================] - 0s 673us/step - loss: 0.3942 - acc: 0.8326
Epoch 8/20
232/232 [==============================] - 0s 679us/step - loss: 0.3933 - acc: 0.8321
Epoch 9/20
232/232 [==============================] - 0s 757us/step - loss: 0.3938 - acc: 0.8322
Epoch 10/20
232/232 [==============================] - 0s 902us/step - loss: 0.3935 - acc: 0.8319
Epoch 11/20
232/232 [==============================] - 0s 729us/step - loss: 0.3933 - acc: 0.8318
Epoch 12/20
232/232 [==============================] - 0s 833us/step - loss: 0.3926 - acc: 0.8319
Epoch 13/20
232/232 [==============================] - 0s 779us/step - loss: 0.3925 - acc: 0.8326
Epoch 14/20
232/232 [==============================] - 0s 766us/step - loss: 0.3931 - acc: 0.8321
Epoch 15/20
232/232 [==============================] - 0s 711us/step - loss: 0.3934 - acc: 0.8313
Epoch 16/20
232/232 [==============================] - 0s 638us/step - loss: 0.3928 - acc: 0.8321
Epoch 17/20
232/232 [==============================] - 0s 667us/step - loss: 0.3933 - acc: 0.8317
Epoch 18/20
232/232 [==============================] - 0s 678us/step - loss: 0.3935 - acc: 0.8322
Epoch 19/20
232/232 [==============================] - 0s 628us/step - loss: 0.3930 - acc: 0.8323
Epoch 20/20
232/232 [==============================] - 0s 642us/step - loss: 0.3930 - acc: 0.8320
1856/1856 [==============================] - 1s 412us/step
Epoch 1/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0324 - acc: 1.0000
Epoch 2/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0267 - acc: 1.0000
Epoch 3/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0228 - acc: 1.0000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0199 - acc: 1.0000
Epoch 5/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0177 - acc: 1.0000
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0159 - acc: 1.0000
Epoch 7/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0144 - acc: 1.0000
Epoch 8/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0132 - acc: 1.0000
Epoch 9/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0122 - acc: 1.0000
Epoch 10/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0113 - acc: 1.0000
Epoch 11/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0106 - acc: 1.0000
Epoch 12/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0099 - acc: 1.0000
Epoch 13/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0093 - acc: 1.0000
Epoch 14/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0088 - acc: 1.0000
Epoch 15/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0084 - acc: 1.0000
Epoch 16/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0079 - acc: 1.0000
Epoch 17/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0076 - acc: 1.0000
Epoch 18/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0072 - acc: 1.0000
Epoch 19/20
1/1 [==============================] - 0s 2ms/step - loss: 0.0069 - acc: 1.0000
Epoch 20/20
1/1 [==============================] - 0s 3ms/step - loss: 0.0066 - acc: 1.0000
1856/1856 [==============================] - 1s 411us/step

array([0.83116949, 0.83234824, 0.83495832, 0.83315652, 0.83009177])

In [47]:
df["diabetes"].value_counts()

3.0    246988
1.0     42095
4.0      5546
2.0      2298
Name: diabetes, dtype: int64

In [92]:
def test_model(hidden_layers, nodes, biases, disease, folds = 5):
    assert hidden_layers == len(nodes) - 1 or hidden_layers == 0
    assert hidden_layers == len(biases) - 2 or hidden_layers == 0
    ##Create func_model from params
    tf.random.set_seed(42)
    func_model = Sequential()
    ##Input layer
    func_model.add(Dense(nodes[0], use_bias = biases[0], input_dim = 15))
    ##Hidden layers
    if hidden_layers != 0:
        for i in range(hidden_layers - 2):
            func_model.add(Dense(nodes[i + 1], use_bias = biases[i + 1]))
    ##Output layers
    func_model.add(Dense(1, use_bias=biases[hidden_layers + 1], activation='sigmoid'))
    func_model.compile(loss="binary_crossentropy", optimizer=tf.keras.optimizers.SGD(
    learning_rate=0.001, momentum=0.0, nesterov=False, name="SGD"), metrics=['acc'])
    accuracy = np.ones(folds)
    #Splits for cross validation
    shuffled = df.sample(len(df.index), replace=True)
    fold_size = len(shuffled.index) // folds
    ##Cross-validation
    for i in range(folds):
        test_fold = shuffled.iloc[i * fold_size:(i + 1) * fold_size]
        rest = shuffled.iloc[(i + 1) * fold_size:]
        test_y = test_fold[disease]
        rest_y = rest[disease]
        vec = DictVectorizer()
        train_dict = rest.drop(_diseases, axis = 1).to_dict('records')
        train_vectorized = vec.fit_transform(train_dict).toarray()
        test_dict = test_fold.drop(_diseases, axis = 1).to_dict('records')
        test_vectorized = vec.fit_transform(test_dict).toarray()
        func_model.fit(train_vectorized, rest_y, epochs=20, batch_size=256, verbose = 1)
        test_pred = func_model.predict(test_vectorized)
        test_pred = test_pred.reshape(-1)
        accuracy[i] = np.count_nonzero(np.round(test_y) == np.round(test_pred)) / len(test_pred)
    return accuracy

In [90]:
def test_diabetes_model(hidden_layers, nodes, biases, disease = 'diabetes', folds = 5):
    assert hidden_layers == len(nodes) - 1 or hidden_layers == 0
    assert hidden_layers == len(biases) - 2 or hidden_layers == 0
    ##Create func_model from params
    tf.random.set_seed(42)
    func_model = Sequential()
    ##Input layer
    func_model.add(Dense(nodes[0], use_bias = biases[0], input_dim = 15))
    ##Hidden layers
    if hidden_layers != 0:
        for i in range(hidden_layers - 2):
            func_model.add(Dense(nodes[i + 1], use_bias = biases[i + 1]))
    ##Output layers
    func_model.add(Dense(3, use_bias=biases[hidden_layers + 1], activation='sigmoid'))
    func_model.compile(loss="binary_crossentropy", optimizer=tf.keras.optimizers.SGD(
    learning_rate=0.001, momentum=0.0, nesterov=False, name="SGD"), metrics=['acc'])
    accuracy = np.ones(folds)
    #Splits for cross validation
    shuffled = df.sample(len(df.index), replace=True)
    shuffled["diabetes"].replace({1: 'Yes', 2: 'Kinda', 3: 'No', 4: 'Kinda'}, inplace = True)
    fold_size = len(shuffled.index) // folds
    ##Cross-validation
    for i in range(folds):
        test_fold = shuffled.iloc[i * fold_size:(i + 1) * fold_size]
        rest = shuffled.iloc[(i + 1) * fold_size:]
        test_y = test_fold[[disease]]
        rest_y = rest[[disease]]
        vec = DictVectorizer()
        test_y_dict = test_y.to_dict('records')
        test_y_vec = vec.fit_transform(test_y_dict).toarray()
        rest_y_dict = test_y.to_dict('records')
        rest_y_vec = vec.fit_transform(rest_y_dict).toarray()
        train_dict = rest.drop(_diseases, axis = 1).to_dict('records')
        train_vectorized = vec.fit_transform(train_dict).toarray()
        test_dict = test_fold.drop(_diseases, axis = 1).to_dict('records')
        test_vectorized = vec.fit_transform(test_dict).toarray()
        func_model.fit(train_vectorized, rest_y, epochs=20, batch_size=256, verbose = 1)
        test_pred = func_model.predict(test_vectorized)
        test_pred = test_pred.reshape(-1)
        accuracy[i] = np.count_nonzero(np.round(test_y) == np.round(test_pred)) / len(test_pred)
    return accuracy

In [91]:
test_diabetes_model(2, [32, 32, 32], [1, 1, 1, 1])

Epoch 1/20

ValueError: in user code:

    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/engine/training.py", line 890, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/engine/training.py", line 948, in compute_loss
        return self.compiled_loss(
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/losses.py", line 139, in __call__
        losses = call_fn(y_true, y_pred)
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/losses.py", line 243, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/losses.py", line 1930, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "/Users/willrathgeb/opt/anaconda3/envs/deep_learning/lib/python3.10/site-packages/keras/backend.py", line 5283, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)

    ValueError: `logits` and `labels` must have the same shape, received ((None, 3) vs (None, 1)).

In [96]:
old_people = df[(df["age"] >= 50) & (df["age"] <= 70)]
old_people

,high_bp,bp_meds,sex,high_chol,heart_attack,stroke,diabetes,smoke_100,smoke_freq,drinking,age,daily_fruit,daily_veg,weekly_phys,race,height,weight,BMI
0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,1.0,3.0,0.0,63.0,0.50,2.17,3.0,1.0,70.0,280.0,40.259821
1,3.0,2.0,2.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,52.0,0.24,0.78,1.0,1.0,68.0,165.0,25.140621
3,1.0,1.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0,0.0,63.0,1.00,0.20,3.0,1.0,67.0,180.0,28.250932
6,1.0,1.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0,0.0,70.0,1.29,1.14,1.0,4.0,66.0,148.0,23.937772
9,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,3.0,0.0,68.0,1.14,3.14,1.0,1.0,67.0,161.0,25.268890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441441,1.0,1.0,1.0,2.0,0.0,0.0,0.0,2.0,3.0,0.0,63.0,0.14,1.71,3.0,5.0,72.0,230.0,31.258831
441442,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0,3.0,0.0,59.0,0.29,0.85,3.0,5.0,66.0,145.0,23.452547
441445,3.0,2.0,1.0,2.0,0.0,0.0,0.0,2.0,3.0,0.0,68.0,0.60,1.07,3.0,5.0,75.0,220.0,27.555611
441454,1.0,1.0,1.0,2.0,0.0,0.0,0.0,2.0,3.0,0.0,52.0,2.00,1.35,3.0,5.0,71.0,166.0,23.200710
441455,1.0,1.0,2.0,1.0,1.0,0.0,1.0,2.0,3.0,0.0,63.0,2.00,0.71,2.0,5.0,62.0,135.0,24.743451